services:
  nsd-zoneloader:
    build:
      dockerfile: ./dockerfiles/Dockerfile.nsd
    hostname: nsd-zoneloader
    image: "nsd-stiab:latest"
    networks:
      stiabnet:
        ipv4_address: 172.20.0.10
    volumes:
      - ./files/nsd-zoneloader/nsd.conf:/etc/nsd/nsd.conf:ro
      - ./files/nsd-zoneloader/keys:/var/lib/stiab/keys:rw
      - ./files/nsd-zoneloader/zones:/var/lib/stiab/zones:rw
  knot-signer:
    build:
      dockerfile: ./dockerfiles/Dockerfile.knotd
    hostname: knot-signer
    image: "knotd-stiab:latest"
    depends_on:
      - nsd-zoneloader
    networks:
      stiabnet:
        ipv4_address: 172.20.0.11
    volumes:
      - ./files/knot-signer/knot.conf:/etc/knot/knot.conf:ro
      - ./files/knot-signer/journal:/var/lib/knot/journal:rw
      - ./files/knot-signer/zones:/var/lib/knot/zones:rw
      - ./files/knot-signer/keys:/var/lib/knot/keys:rw
  knot-fakeroot:
    build:
      dockerfile: ./dockerfiles/Dockerfile.knotd
    hostname: knot-fakeroot
    image: "knotd-stiab:latest"
    networks:
      stiabnet:
        ipv4_address: 172.20.0.13
    volumes:
      - ./files/knot-fakeroot/knot.conf:/etc/knot/knot.conf:ro
      - ./files/knot-fakeroot/journal:/var/lib/knot/journal:rw
      - ./files/knot-fakeroot/zones:/var/lib/knot/zones:rw
      - ./files/knot-fakeroot/keys:/var/lib/knot/keys:rw
  nsd-validator:
    build:
      dockerfile: ./dockerfiles/Dockerfile.nsd
    hostname: nsd-validator
    image: "nsd-stiab:latest"
    depends_on:
      - knot-signer
    networks:
      stiabnet:
        ipv4_address: 172.20.0.12
    volumes:
      - ./files/nsd-validator/nsd.conf:/etc/nsd/nsd.conf:ro
      - ./files/nsd-validator/keys:/var/lib/stiab/keys:rw
      - ./files/nsd-validator/zones:/var/lib/stiab/zones:rw
      - ./files/knot-signer/knot.conf:/etc/knot/knot.conf:ro  # Needed for ksignzone -v
      - ./files/nsd-validator/verify.sh:/etc/nsd/verify.sh:ro # Wrapper script to catch stdin and start other verifiers
  nsd-dister:
    build:
      dockerfile: ./dockerfiles/Dockerfile.nsd
    hostname: nsd-dister
    image: "nsd-stiab:latest"
    depends_on:
      - nsd-validator
    networks:
      stiabnet:
        ipv4_address: 172.20.0.14
    volumes:
      - ./files/nsd-dister/nsd.conf:/etc/nsd/nsd.conf:ro
      - ./files/nsd-dister/keys:/var/lib/stiab/keys:rw
      - ./files/nsd-dister/zones:/var/lib/stiab/zones:rw
  unbound-recursor:
    build:
      dockerfile: ./dockerfiles/Dockerfile.unbound
    hostname: unbound-recursor
    image: "unbound-stiab:latest"
    depends_on:
      - nsd-dister
    networks:
      stiabnet:
        ipv4_address: 172.20.0.15
    volumes:
      - ./files/unbound-recursor/conf:/etc/unbound/:ro
  dns-client:
    build:
      dockerfile: ./dockerfiles/Dockerfile.dnsclient
    hostname: dns-client
    image: "dnsclient-stiab:latest"
    depends_on:
      - unbound-recursor
    networks:
      stiabnet:
        ipv4_address: 172.20.0.16
    volumes:
      - ./files/dns-client/conf:/var/lib/dns/conf:ro
      - ./files/dns-client/results:/var/lib/dns/results:rw
  knot-secondlevel:
    build:
      dockerfile: ./dockerfiles/Dockerfile.knotd
    hostname: knot-secondlevel
    image: "knotd-stiab:latest"
    networks:
      stiabnet:
        ipv4_address: 172.20.0.17
    volumes:
      - ./files/knot-secondlevel/knot.conf:/etc/knot/knot.conf:ro
      - ./files/knot-secondlevel/journal:/var/lib/knot/journal:rw
      - ./files/knot-secondlevel/zones:/var/lib/knot/zones:rw
      - ./files/knot-secondlevel/keys:/var/lib/knot/keys:rw
  nitrokey-nethsm:
    hostname: nitrokey-nethsm
    image: "docker.io/nitrokey/nethsm:testing"
    networks:
      stiabnet:
        ipv4_address: 172.20.0.18
    volumes:
      - ./files/nitrokey-nethsm/data:/data:rw
  hsm-client:
    build:
      dockerfile: ./dockerfiles/Dockerfile.hsmclient
    hostname: hsm-client
    image: "hsmclient-stiab:latest"
    depends_on:
      - nitrokey-nethsm
    networks:
      stiabnet:
        ipv4_address: 172.20.0.19
  knot-secondlevel-hsmsigned:
    build:
      dockerfile: ./dockerfiles/Dockerfile.knotd
    hostname: knot-secondlevel-hsmsigned
    image: "knotd-stiab:latest"
    depends_on:
      - hsm-client
    networks:
      stiabnet:
        ipv4_address: 172.20.0.20
    volumes:
      - ./files/knot-secondlevel-hsmsigned/knot.conf:/etc/knot/knot.conf:ro
      - ./files/knot-secondlevel-hsmsigned/journal:/var/lib/knot/journal:rw
      - ./files/knot-secondlevel-hsmsigned/zones:/var/lib/knot/zones:rw
      - ./files/knot-secondlevel-hsmsigned/nethsm-pkcs11-vv1.6.0-x86_64-ubuntu.24.04.so:/usr/local/lib/nethsm/nethsm-pkcs11-vv1.6.0-x86_64-ubuntu.24.04.so:ro
      - ./files/knot-secondlevel-hsmsigned/p11nethsm.conf:/usr/local/etc/nitrokey/p11nethsm.conf:ro
networks:
  stiabnet:
    enable_ipv6: false
    ipam:
      config:
      - subnet: 172.20.0.0/24
